# CC=g++
# CFLAGS=-O3
# CFLAGS=
# SOURCES=game.cpp
# OBJECTS=$(SOURCES:.cpp=.o)
# EXECUTABLE=../game

# all: $(SOURCES) $(EXECUTABLE)

# $(EXECUTABLE): $(OBJECTS)
# 	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

# .cpp.o:
# 	$(CC) $(CFLAGS) $< -o $@
all: game.out

game.out:
	g++ game.cpp -O3 -o game.out